development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: healthy
  pool: 5
  username: root
  password: Nmt#kms54
  host: localhost

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: healthy
  pool: 5
  username: root
  password: Nmt#kms54
  host: localhost

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: healthy
  pool: 5
  username: root
  password: Nmt#kms54
  host: localhost
